# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import glossario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsw', models.TextField(blank=True, default=b'', verbose_name=b'BSW')),
                ('imagem', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'configura\xe7\xf5es de m\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Glossario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome do Gloss\xc3\xa1rio')),
                ('descricao', models.TextField(default=b'', verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('imagem', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Imagem')),
                ('link', models.CharField(max_length=20, verbose_name=b'Link')),
                ('dataCriacao', models.DateField(auto_now_add=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o')),
                ('videoGlossario', glossario.models.Video(blank=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo')),
                ('membros', models.ManyToManyField(blank=True, related_name='glossario_membros', to=settings.AUTH_USER_MODEL, verbose_name=b'membros')),
                ('responsavel', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'respons\xc3\xa1vel')),
            ],
            options={
                'verbose_name': 'gloss\xe1rio',
            },
        ),
        migrations.CreateModel(
            name='GrupoCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to=b'')),
                ('bsw', models.TextField(verbose_name=b'BSW')),
            ],
            options={
                'verbose_name_plural': 'Grupos de configura\xe7\xe3o de m\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('bsw', models.TextField(verbose_name=b'BSW')),
                ('imagem', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Imagem')),
                ('areaClicavel', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'localiza\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattes', models.CharField(blank=True, max_length=200, verbose_name=b'Curr\xc3\xadculo Lattes')),
                ('foto', models.ImageField(blank=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traducaoP', models.CharField(max_length=30, verbose_name=b'palavra')),
                ('traducaoI', models.CharField(max_length=30, verbose_name=b'word')),
                ('bsw', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=200, null=True, verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('dataPost', models.DateField(null=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o')),
                ('publicado', models.BooleanField(default=False)),
                ('sinalLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo do sinal')),
                ('descLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo da descri\xc3\xa7\xc3\xa3o')),
                ('exemploLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo do exemplo')),
                ('varicLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo da varia\xc3\xa7\xc3\xa3o')),
                ('cmD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Direita', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o da m\xc3\xa3o direita')),
                ('cmE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Esquerda', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o da m\xc3\xa3o esquerda')),
                ('glossario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Glossario', verbose_name=b'gloss\xc3\xa1rio')),
                ('grupoCMd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Direita', to='glossario.GrupoCM', verbose_name=b'grupo da m\xc3\xa3o direita')),
                ('grupoCMe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Esquerda', to='glossario.GrupoCM', verbose_name=b'grupo da m\xc3\xa3o esquerda')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Localizacao', verbose_name=b'localiza\xc3\xa7\xc3\xa3o')),
                ('postador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sinais',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('video', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Imagem')),
                ('temaPai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema', verbose_name=b'Tema Pai')),
            ],
        ),
        migrations.AddField(
            model_name='sinal',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema'),
        ),
        migrations.AddField(
            model_name='cm',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossario.GrupoCM', verbose_name=b'Grupo de Configura\xc3\xa7\xc3\xa3o de M\xc3\xa3o'),
        ),
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together=set([('traducaoP', 'traducaoI', 'grupoCMe', 'cmE', 'grupoCMd', 'cmD', 'localizacao')]),
        ),
    ]
