# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 14:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import glossario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=200, verbose_name=b'Nome')),
                ('latte', models.CharField(max_length=300, verbose_name=b'Curr\xc3\xadculo Latte')),
                ('foto', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', glossario.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsw', models.TextField(blank=True, default=b'', verbose_name=b'BSW')),
                ('imagem', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'configura\xe7\xf5es de m\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Glossario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome do Gloss\xc3\xa1rio')),
                ('descricao', models.TextField(default=b'', verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('imagem', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Imagem')),
                ('link', models.CharField(max_length=20, verbose_name=b'Link')),
                ('dataCriacao', models.DateField(auto_now_add=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o')),
                ('videoGlossario', glossario.models.Video(blank=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo')),
                ('membros', models.ManyToManyField(blank=True, related_name='glossario_membros', to=settings.AUTH_USER_MODEL, verbose_name=b'membros')),
                ('responsavel', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'respons\xc3\xa1vel')),
            ],
            options={
                'verbose_name': 'gloss\xe1rio',
            },
        ),
        migrations.CreateModel(
            name='GrupoCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to=b'')),
                ('bsw', models.TextField(verbose_name=b'BSW')),
            ],
            options={
                'verbose_name_plural': 'Grupos de configura\xe7\xe3o de m\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('bsw', models.TextField(verbose_name=b'BSW')),
                ('imagem', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Imagem')),
                ('areaClicavel', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'localiza\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Sinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traducaoP', models.CharField(max_length=30, verbose_name=b'palavra')),
                ('traducaoI', models.CharField(max_length=30, verbose_name=b'word')),
                ('bsw', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('dataPost', models.DateField(verbose_name=b'data de cria\xc3\xa7\xc3\xa3o')),
                ('publicado', models.BooleanField(default=False)),
                ('sinalLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo do Sinal')),
                ('descLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo da Descri\xc3\xa7\xc3\xa3o')),
                ('exemploLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo do Exemplo')),
                ('varicLibras', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo da Varia\xc3\xa7\xc3\xa3o')),
                ('cmD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Direita', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o direita')),
                ('cmE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Esquerda', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o esquerda')),
                ('glossario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossario.Glossario', verbose_name=b'gloss\xc3\xa1rio')),
                ('grupoCMd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Direita', to='glossario.GrupoCM', verbose_name=b'grupo de configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o direita')),
                ('grupoCMe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Esquerda', to='glossario.GrupoCM', verbose_name=b'grupo de configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o esquerda')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Localizacao', verbose_name=b'localiza\xc3\xa7\xc3\xa3o')),
                ('postador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sinais',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('video', glossario.models.Video(blank=True, null=True, upload_to=b'', verbose_name=b'V\xc3\xaddeo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Imagem')),
                ('temaPai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema', verbose_name=b'Tema Pai')),
            ],
        ),
        migrations.AddField(
            model_name='sinal',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema'),
        ),
        migrations.AddField(
            model_name='cm',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossario.GrupoCM', verbose_name=b'Grupo de Configura\xc3\xa7\xc3\xa3o de M\xc3\xa3o'),
        ),
    ]
