# Generated by Django 2.1 on 2018-10-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='imagem',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
