# Generated by Django 2.1 on 2018-12-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(choices=[('1', 'Sem Movimentação'), ('2', 'Parede'), ('3', 'Chão'), ('4', 'Circular'), ('5', 'Contato')], default='sem', max_length=10),
        ),
    ]
