# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm',
            name='bsw',
            field=models.TextField(blank=True, default=b'', verbose_name=b'BSW'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='dataCriacao',
            field=models.DateField(auto_now_add=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='membros',
            field=models.ManyToManyField(related_name='glossario_membros', to=settings.AUTH_USER_MODEL, verbose_name=b'membros'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'respons\xc3\xa1vel'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='cmD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Direita', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o direita'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='cmE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Esquerda', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o esquerda'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='dataPost',
            field=models.DateField(verbose_name=b'data de cria\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='glossario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossario.Glossario', verbose_name=b'gloss\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='grupoCMd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Direita', to='glossario.GrupoCM', verbose_name=b'grupo configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o direita'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='grupoCMe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_M_Esquerda', to='glossario.GrupoCM', verbose_name=b'grupo configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o esquerda'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Localizacao', verbose_name=b'localiza\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='traducaoI',
            field=models.CharField(max_length=30, verbose_name=b'word'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='traducaoP',
            field=models.CharField(max_length=30, verbose_name=b'palavra'),
        ),
    ]
