# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='cmD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Direita', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o direita'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='cmE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Esquerda', to='glossario.CM', verbose_name=b'configura\xc3\xa7\xc3\xa3o de m\xc3\xa3o esquerda'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='dataPost',
            field=models.DateField(blank=True, null=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o'),
        ),
    ]
