# Generated by Django 2.1 on 2018-10-09 18:59

from django.db import migrations
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='varicLibras',
            field=glossario.models.Video(blank=True, null=True, upload_to=glossario.models.sinal_upload_path, verbose_name='Vídeo da variante'),
        ),
    ]
