# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together=set([('traducaoP', 'traducaoI')]),
        ),
    ]
