# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, upload_to=b"{% static 'img/profile_images/%s' % user.username %}"),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='descLibras',
            field=glossario.models.Video(blank=True, null=True, upload_to=b"{% static 'img/sinaisEnviados_videos/%s' % self.traducaoP %}", verbose_name=b'V\xc3\xaddeo da descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='exemploLibras',
            field=glossario.models.Video(blank=True, null=True, upload_to=b"{% static 'img/sinaisEnviados_videos/%s' % self.traducaoP %}", verbose_name=b'V\xc3\xaddeo do exemplo'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='sinalLibras',
            field=glossario.models.Video(blank=True, null=True, upload_to=b"{% static 'img/sinaisEnviados_videos/%s' % self.traducaoP %}", verbose_name=b'V\xc3\xaddeo do sinal'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='varicLibras',
            field=glossario.models.Video(blank=True, null=True, upload_to=b"{% static 'img/sinaisEnviados_videos/%s' % self.traducaoP %}", verbose_name=b'V\xc3\xaddeo da varia\xc3\xa7\xc3\xa3o'),
        ),
    ]
