# Generated by Django 2.1 on 2018-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(choices=[('sem', 'Sem Movimentação'), ('parede', 'Parede'), ('chao', 'Chão'), ('circular', 'Circular'), ('contato', 'Contato')], default='sem', max_length=10),
        ),
        migrations.AlterField(
            model_name='tema',
            name='imagem',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
