# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm',
            options={'verbose_name_plural': 'configura\xe7\xf5es de m\xe3o'},
        ),
        migrations.AlterModelOptions(
            name='glossario',
            options={'verbose_name': 'gloss\xe1rio'},
        ),
        migrations.AlterModelOptions(
            name='grupocm',
            options={'verbose_name_plural': 'Grupos de configura\xe7\xe3o de m\xe3o'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name_plural': 'localiza\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='sinal',
            options={'verbose_name_plural': 'sinais'},
        ),
    ]
