# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0002_auto_20170710_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='postador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema'),
        ),
    ]
