# Generated by Django 2.1 on 2019-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0002_auto_20181206_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(choices=[('1', 'Sem Movimentação'), ('2', 'Parede'), ('3', 'Chão'), ('4', 'Circular'), ('5', 'Contato')], default=1, max_length=10),
        ),
    ]
