# Generated by Django 2.2.3 on 2019-09-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0002_auto_20190906_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together=set(),
        ),
    ]
