# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0002_auto_20170622_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossario',
            name='descricao',
            field=models.TextField(default=b'', verbose_name=b'descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='glossario_membros', to=settings.AUTH_USER_MODEL, verbose_name=b'membros'),
        ),
    ]
