# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0003_auto_20170710_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='glossario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Glossario', verbose_name=b'gloss\xc3\xa1rio'),
        ),
    ]
