# Generated by Django 2.2.3 on 2019-09-13 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0003_auto_20190907_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='cmD',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Direita', to='glossario.CM', verbose_name='configuração da mão direita'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='cmE',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='C_M_Esquerda', to='glossario.CM', verbose_name='configuração da mão esquerda'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma'), ('4', 'Cabeça'), ('12', 'Ombros'), ('3', 'Braços'), ('6', 'Nariz'), ('2', 'Bochechas'), ('1', 'Boca'), ('16', 'Tronco'), ('10', 'Espaço Neutro'), ('11', 'Olhos'), ('17', 'Orelhas'), ('13', 'Pescoço'), ('14', 'Queixo'), ('15', 'Testa'), ('5', 'Mãos')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(blank=True, choices=[('', 'Sem Movimentação'), ('1', 'Parede'), ('2', 'Chão'), ('3', 'Circular'), ('4', 'Contato')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='postador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
