# Generated by Django 2.1 on 2019-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0003_auto_20190321_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='descricao',
            field=models.TextField(null=True, verbose_name='descrição'),
        ),
    ]
