# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0004_auto_20170710_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='dataPost',
            field=models.DateField(null=True, verbose_name=b'data de cria\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='glossario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Glossario', verbose_name=b'gloss\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='postador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossario.Tema'),
        ),
    ]
