# Generated by Django 2.2 on 2019-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0004_auto_20190402_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='localizacao',
            field=models.CharField(choices=[('0', 'Nunhuma'), ('1', 'Cabeça'), ('2', 'Ombros'), ('3', 'Braços'), ('4', 'Nariz'), ('5', 'Bochechas'), ('6', 'Boca'), ('7', 'Tronco'), ('8', 'Espaço Neutro'), ('9', 'Olhos'), ('10', 'Orelhas'), ('11', 'Pescoço'), ('12', 'Queixo'), ('13', 'Testa')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(choices=[('0', 'Sem Movimentação'), ('1', 'Parede'), ('2', 'Chão'), ('3', 'Circular'), ('4', 'Contato')], default=0, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together={('traducaoP', 'traducaoI', 'grupoCMe', 'cmE', 'grupoCMd', 'cmD', 'localizacao', 'movimentacao')},
        ),
    ]
