# Generated by Django 2.2.3 on 2020-01-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0005_auto_20190913_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='userglossario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
