# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0005_auto_20170724_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, upload_to=b'profile_upload_path'),
        ),
    ]
