# Generated by Django 2.2 on 2019-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0005_auto_20190415_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cm',
            name='grupo',
        ),
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together={('traducaoP', 'traducaoI', 'cmE', 'cmD', 'localizacao', 'movimentacao')},
        ),
        migrations.RemoveField(
            model_name='sinal',
            name='grupoCMd',
        ),
        migrations.RemoveField(
            model_name='sinal',
            name='grupoCMe',
        ),
        migrations.DeleteModel(
            name='GrupoCM',
        ),
    ]
