# Generated by Django 2.2 on 2019-05-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0006_auto_20190506_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarraPesquisa',
        ),
        migrations.AlterModelOptions(
            name='userglossario',
            options={'verbose_name': 'Usuário'},
        ),
    ]
