# Generated by Django 2.2 on 2020-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0006_auto_20200123_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userglossario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
