# Generated by Django 2.2 on 2020-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0007_auto_20200207_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossario',
            options={'ordering': ['nome'], 'verbose_name': 'Glossário'},
        ),
        migrations.AlterField(
            model_name='glossario',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Um glossário com este nome já existe.'}, max_length=100, unique=True, verbose_name='Nome do Glossário'),
        ),
    ]
