# Generated by Django 2.2 on 2019-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0007_auto_20190624_1717'),
        ('glossario', '0007_auto_20190528_1844'),
    ]

    operations = [
    ]
