# Generated by Django 2.2 on 2020-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0007_auto_20200207_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Glossário'),
        ),
    ]
