# Generated by Django 2.2 on 2019-06-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0008_merge_20190624_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userglossario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userglossario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
