# Generated by Django 2.2 on 2020-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0008_auto_20200728_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='nome',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=100, unique=True, verbose_name='Nome do Glossário'),
        ),
    ]
