# Generated by Django 2.2 on 2020-08-24 17:35

from django.db import migrations, models
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0008_auto_20200817_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinal',
            options={'ordering': ['portugues'], 'verbose_name_plural': 'sinais'},
        ),
        migrations.AddField(
            model_name='sinal',
            name='preview1',
            field=models.FileField(blank=True, null=True, upload_to=glossario.models.preview_upload_path, verbose_name='Preview1'),
        ),
        migrations.AddField(
            model_name='sinal',
            name='preview2',
            field=models.FileField(blank=True, null=True, upload_to=glossario.models.preview_upload_path, verbose_name='Preview2'),
        ),
        migrations.AddField(
            model_name='sinal',
            name='preview3',
            field=models.FileField(blank=True, null=True, upload_to=glossario.models.preview_upload_path, verbose_name='Preview3'),
        ),
        migrations.AddField(
            model_name='sinal',
            name='preview4',
            field=models.FileField(blank=True, null=True, upload_to=glossario.models.preview_upload_path, verbose_name='Preview4'),
        ),
    ]
