# Generated by Django 2.2 on 2019-07-03 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0009_auto_20190627_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinal',
            name='dataPost',
        ),
        migrations.AddField(
            model_name='sinal',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
