# Generated by Django 2.2 on 2020-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0009_auto_20200728_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Um glossário com este nome já existe.'}, max_length=100, unique=True, verbose_name='Nome do Glossário'),
        ),
    ]
