# Generated by Django 2.2 on 2020-10-14 18:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_auto_20200826_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma'), ('4', 'Cabeça'), ('12', 'Ombros'), ('3', 'Braços'), ('6', 'Nariz'), ('2', 'Bochechas'), ('1', 'Boca'), ('16', 'Tronco'), ('10', 'Espaço Neutro'), ('11', 'Olhos'), ('17', 'Orelhas'), ('13', 'Pescoço'), ('14', 'Queixo'), ('15', 'Testa'), ('5', 'Mãos')], default='', max_length=2, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(blank=True, choices=[('0', 'Sem Movimentação'), ('1', 'Parede'), ('2', 'Chão'), ('3', 'Circular'), ('4', 'Contato')], default='', max_length=10, null=True, verbose_name='Movimento'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Uma área com este nome já existe.'}, max_length=20, unique=True, verbose_name='Nome da Área')),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='glossario.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='glossario',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='glossario.Area', verbose_name='Área'),
        ),
        migrations.AlterUniqueTogether(
            name='glossario',
            unique_together={('nome', 'area')},
        ),
    ]
