# Generated by Django 2.2 on 2020-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_auto_20200826_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma'), ('4', 'Cabeça'), ('12', 'Ombros'), ('3', 'Braços'), ('6', 'Nariz'), ('2', 'Bochechas'), ('1', 'Boca'), ('16', 'Tronco'), ('10', 'Espaço Neutro'), ('11', 'Olhos'), ('17', 'Orelhas'), ('13', 'Pescoço'), ('14', 'Queixo'), ('15', 'Testa'), ('5', 'Mãos')], default='', max_length=2, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='movimentacao',
            field=models.CharField(blank=True, choices=[('0', 'Sem Movimentação'), ('1', 'Parede'), ('2', 'Chão'), ('3', 'Circular'), ('4', 'Contato')], default='', max_length=10, null=True, verbose_name='Movimento'),
        ),
    ]
