# Generated by Django 2.2.3 on 2019-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_auto_20190702_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='Preview do Video de sinal'),
        ),
    ]
