# Generated by Django 2.2 on 2020-07-28 20:21

from django.db import migrations
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_auto_20200728_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='nome',
            field=glossario.models.NameField(error_messages={'unique': 'Um glossário com este nome já existe.'}, max_length=100, unique=True, verbose_name='Nome do Glossário'),
        ),
    ]
