# Generated by Django 2.1 on 2019-08-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0010_auto_20190702_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossario',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visivel'),
        ),
    ]
