# Generated by Django 2.1 on 2019-08-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0011_sinal_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm',
            options={'verbose_name_plural': 'Configurações de mão'},
        ),
        migrations.RemoveField(
            model_name='cm',
            name='imagem',
        ),
        migrations.AddField(
            model_name='cm',
            name='group',
            field=models.TextField(default='', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='cm',
            name='name',
            field=models.TextField(default='', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cm',
            name='bsw',
            field=models.TextField(blank=True, default='0', verbose_name='BSW'),
        ),
    ]
