# Generated by Django 2.2 on 2020-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0011_auto_20200827_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('0', 'Superior'), ('1', 'Fundamental')], default='0', max_length=20)),
            ],
            options={
                'verbose_name': 'Área do Conhecimento',
            },
        ),
        migrations.AddField(
            model_name='glossario',
            name='area',
            field=models.ManyToManyField(to='glossario.AreaConhecimento', verbose_name='area do conhecimento'),
        ),
    ]
