# Generated by Django 2.1 on 2019-08-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0011_sinal_preview'),
        ('glossario', '0011_glossario_visivel'),
    ]

    operations = [
    ]
