# Generated by Django 2.2 on 2020-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0012_auto_20200922_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaconhecimento',
            name='area',
        ),
        migrations.RemoveField(
            model_name='glossario',
            name='area',
        ),
        migrations.AddField(
            model_name='glossario',
            name='area',
            field=models.CharField(choices=[('0', 'Superior'), ('1', 'Fundamental')], default='', max_length=20),
        ),
    ]
