# Generated by Django 2.1 on 2019-08-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0012_auto_20190808_2130'),
        ('glossario', '0012_merge_20190802_1814'),
    ]

    operations = [
    ]
