# Generated by Django 2.2 on 2020-11-09 12:33

from django.db import migrations, models
import django.db.models.deletion
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0012_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome'], 'verbose_name': 'Área'},
        ),
        migrations.AlterField(
            model_name='glossario',
            name='area',
            field=models.ForeignKey(default=glossario.models.Glossario.get_default_area, on_delete=django.db.models.deletion.SET_DEFAULT, to='glossario.Area', verbose_name='Área'),
        ),
    ]
