# Generated by Django 2.2 on 2020-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_auto_20201109_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['criado_em'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterField(
            model_name='userglossario',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
