# Generated by Django 2.2 on 2020-10-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_auto_20201021_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome'], 'verbose_name': 'Área'},
        ),
    ]
