# Generated by Django 2.2 on 2020-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_auto_20201021_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome'], 'verbose_name': 'Área'},
        ),
        migrations.AlterField(
            model_name='userglossario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
