# Generated by Django 2.2.3 on 2019-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_merge_20190816_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm',
            options={'verbose_name_plural': 'Configurações de Mão'},
        ),
        migrations.RemoveField(
            model_name='sinal',
            name='preview',
        ),
    ]
