# Generated by Django 2.2 on 2020-09-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0013_auto_20200922_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoGlossarios',
            fields=[
                ('glossario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='glossario.Glossario')),
                ('grupo_de_glossarios', models.ManyToManyField(blank=True, related_name='grupo_de_glossarios', to='glossario.Glossario')),
            ],
            bases=('glossario.glossario',),
        ),
    ]
