# Generated by Django 2.2.3 on 2019-09-01 00:41

from django.db import migrations, models
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0014_auto_20190830_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinal',
            name='tema',
        ),
        migrations.AlterField(
            model_name='sinal',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='sinalLibras',
            field=models.FileField(null=True, upload_to=glossario.models.sinal_upload_path, verbose_name='Vídeo do sinal'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='traducaoI',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='word'),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
