# Generated by Django 2.2 on 2020-11-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0014_auto_20201116_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userglossario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
