# Generated by Django 2.2.3 on 2019-09-01 01:56

from django.conf import settings
from django.db import migrations, models
import glossario.models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0015_auto_20190831_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossario',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='glossario',
            old_name='videoGlossario',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='create_data',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='traducaoI',
            new_name='ingles',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='traducaoP',
            new_name='portugues',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='descLibras',
            new_name='video_descricao',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='exemploLibras',
            new_name='video_exemplo',
        ),
        migrations.RenameField(
            model_name='sinal',
            old_name='sinalLibras',
            new_name='video_sinal',
        ),
        migrations.RemoveField(
            model_name='glossario',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='glossario',
            name='responsaveis',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='responsaveis'),
        ),
        migrations.AddField(
            model_name='sinal',
            name='video_variacao',
            field=models.FileField(blank=True, null=True, upload_to=glossario.models.sinal_upload_path, verbose_name='Vídeo de variações'),
        ),
        migrations.AlterField(
            model_name='glossario',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='sinal',
            unique_together={('portugues', 'ingles', 'cmE', 'cmD', 'localizacao', 'movimentacao')},
        ),
        migrations.RemoveField(
            model_name='sinal',
            name='varicLibras',
        ),
    ]
