BEGIN TRANSACTION;
insert into glossario_cm ("id", "bsw", "name", "group") values ('1', '100', 'Index', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('2', '101', 'Index on Circle', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('3', '102', 'Index on Cup', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('4', '103', 'Index on Oval', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('5', '104', 'Index on Hinge', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('6', '105', 'Index on Angle', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('7', '106', 'Index Bent', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('8', '107', 'Index Bent on Circle', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('9', '108', 'Index Bent on Fist Thumb Under', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('10', '109', 'Index Raised Knuckle', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('11', '10a', 'Index Cup', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('12', '10b', 'Index Hinge', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('13', '10c', 'Index Hinge Low', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('14', '10d', 'Index Hinge on Circle', '100');
insert into glossario_cm ("id", "bsw", "name", "group") values ('15', '10e', 'Index Middle', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('16', '10f', 'Index Middle on Circle', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('17', '110', 'Index Middle Bent', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('18', '111', 'Index Middle Raised Knuckles', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('19', '112', 'Index Middle Hinge', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('20', '113', 'Index Up - Middle Hinge', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('21', '114', 'Index Hinge - Middle Up', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('22', '115', 'Index Middle Unit', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('23', '116', 'Index Middle Unit - Index Bent', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('24', '117', 'Index Middle Unit - Middle Bent', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('25', '118', 'Index Middle Unit - Cup', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('26', '119', 'Index Middle Unit - Hinge', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('27', '11a', 'Index Middle Cross', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('28', '11b', 'Index Middle Cross on Circle', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('29', '11c', 'Middle Bent Over Index', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('30', '11d', 'Index Bent Over Middle', '10e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('31', '11e', 'Index Middle Thumb', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('32', '11f', 'Index Middle Thumb on Circle', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('33', '120', 'Index Middle Straight - Thumb Bent', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('34', '121', 'Index Middle Bent - Thumb Straight', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('35', '122', 'Index Middle Thumb Bent', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('36', '123', 'Index Middle Hinge Spread - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('37', '124', 'Index Up - Middle Hinge - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('38', '125', 'Index Up - Middle Hinge - Thumb Unit', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('39', '126', 'Index Hinge - Middle Up - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('40', '127', 'Index Middle Up Spread - Thumb Forward', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('41', '128', 'Index Middle Thumb Cup', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('42', '129', 'Index Middle Thumb Circle', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('43', '12a', 'Index Middle Thumb Hook', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('44', '12b', 'Index Middle Thumb Hinge', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('45', '12c', 'Thumb Between Index Middle Straight', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('46', '12d', 'Index Middle Unit - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('47', '12e', 'Index Middle Unit - Thumb Side Unit', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('48', '12f', 'Index Middle Unit - Thumb Side Bent', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('49', '130', 'Middle Thumb Hook - Index Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('50', '131', 'Index Thumb Hook - Middle Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('51', '132', 'Index Middle Unit Hinge - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('52', '133', 'Index Middle Cross - Thumb Side', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('53', '134', 'Index Middle Unit - Thumb Forward', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('54', '135', 'Index Middle Unit Cup - Thumb Forward', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('55', '136', 'Middle Thumb Cup - Index Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('56', '137', 'Index Thumb Cup - Middle Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('57', '138', 'Middle Thumb Circle - Index Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('58', '139', 'Middle Thumb Circle - Index Hinge', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('59', '13a', 'Index Thumb Angle Out - Middle Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('60', '13b', 'Index Thumb Angle In - Middle Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('61', '13c', 'Index Thumb Circle - Middle Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('62', '13d', 'Index Middle Thumb - Unit Hinge', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('63', '13e', 'Index Middle Thumb - Angle Out', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('64', '13f', 'Index Middle Thumb - Angle', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('65', '140', 'Middle Thumb Angle Out - Index Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('66', '141', 'Middle Thumb Angle Out - Index Crossed', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('67', '142', 'Middle Thumb Angle - Index Up', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('68', '143', 'Index Thumb Hook - Middle Hinge', '11e');
insert into glossario_cm ("id", "bsw", "name", "group") values ('69', '144', 'Four Fingers', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('70', '145', 'Four Fingers Bent', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('71', '146', 'Four Fingers Hinge', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('72', '147', 'Four Fingers Unit', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('73', '148', 'Four Fingers Unit Split', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('74', '149', 'Four Fingers Unit Claw', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('75', '14a', 'Four Fingers Unit Bent', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('76', '14b', 'Four Fingers Unit Hinge', '144');
insert into glossario_cm ("id", "bsw", "name", "group") values ('77', '14c', 'Five Fingers Spread', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('78', '14d', 'Five Fingers Spread Heel', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('79', '14e', 'Five Fingers Spread - Four Bent', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('80', '14f', 'Five Fingers Spread - Four Bent Heel', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('81', '150', 'Five Fingers Spread Bent', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('82', '151', 'Five Fingers Spread Bent Heel', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('83', '152', 'Five Fingers Spread - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('84', '153', 'Five Fingers Spread Cup', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('85', '154', 'Five Fingers Spread Cup Open', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('86', '155', 'Five Fingers Spread Hinge Open', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('87', '156', 'Five Fingers Spread Oval', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('88', '157', 'Five Fingers Spread Hinge', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('89', '158', 'Five Fingers Spread Hinge - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('90', '159', 'Five Fingers Spread Hinge - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('91', '15a', 'Flat', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('92', '15b', 'Flat - Between Palm Facings', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('93', '15c', 'Flat Heel', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('94', '15d', 'Flat - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('95', '15e', 'Flat - Thumb Side Heel', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('96', '15f', 'Flat - Thumb Bent', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('97', '160', 'Flat - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('98', '161', 'Flat Split Index - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('99', '162', 'Flat Split Center', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('100', '163', 'Flat Split Center - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('101', '164', 'Flat Split Center - Thumb Side Bent', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('102', '165', 'Flat Split Baby', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('103', '166', 'Claw', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('104', '167', 'Claw - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('105', '168', 'Claw - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('106', '169', 'Claw - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('107', '16a', 'Hook Curlicue', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('108', '16b', 'Hook', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('109', '16c', 'Cup Open', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('110', '16d', 'Cup', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('111', '16e', 'Cup Open - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('112', '16f', 'Cup - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('113', '170', 'Cup Open - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('114', '171', 'Cup - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('115', '172', 'Cup Open - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('116', '173', 'Cup - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('117', '174', 'Curlicue Open', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('118', '175', 'Curlicue', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('119', '176', 'Circle', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('120', '177', 'Oval', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('121', '178', 'Oval - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('122', '179', 'Oval - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('123', '17a', 'Oval - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('124', '17b', 'Hinge Open', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('125', '17c', 'Hinge Open - Thumb Forward', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('126', '17d', 'Hinge', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('127', '17e', 'Hinge Small', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('128', '17f', 'Hinge Open - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('129', '180', 'Hinge - Thumb Side', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('130', '181', 'Hinge Open - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('131', '182', 'Hinge - No Thumb', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('132', '183', 'Hinge - Thumb Side Touches Index', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('133', '184', 'Hinge - Thumb Between Middle Ring', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('134', '185', 'Angle', '14c');
insert into glossario_cm ("id", "bsw", "name", "group") values ('135', '186', 'Index Middle Ring', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('136', '187', 'Index Middle Ring on Circle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('137', '188', 'Index Middle Ring on Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('138', '189', 'Index Middle Ring on Angle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('139', '18a', 'Baby Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('140', '18b', 'Index Middle Ring - Bent', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('141', '18c', 'Index Middle Ring - Unit', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('142', '18d', 'Index Middle Ring - Unit Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('143', '18e', 'Baby Down', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('144', '18f', 'Baby Down - Ripple Straight', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('145', '190', 'Baby Down - Ripple Curved', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('146', '191', 'Baby Down - Others Circle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('147', '192', 'Baby Up', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('148', '193', 'Baby Up on Fist Thumb Under', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('149', '194', 'Baby Up on Circle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('150', '195', 'Baby Up on Oval', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('151', '196', 'Baby Up on Angle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('152', '197', 'Baby Raised Knuckle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('153', '198', 'Baby Bent', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('154', '199', 'Baby Touches Thumb', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('155', '19a', 'Baby Thumb', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('156', '19b', 'Baby Thumb on Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('157', '19c', 'Baby Index Thumb', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('158', '19d', 'Baby Index Thumb on Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('159', '19e', 'Baby Index Thumb - Index Thumb Angle Out', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('160', '19f', 'Baby Index Thumb - Index Thumb Angle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('161', '1a0', 'Baby Index', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('162', '1a1', 'Baby Index on Circle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('163', '1a2', 'Baby Index on Hinge', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('164', '1a3', 'Baby Index on Angle', '186');
insert into glossario_cm ("id", "bsw", "name", "group") values ('165', '1a4', 'Index Middle Baby', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('166', '1a5', 'Index Middle Baby on Circle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('167', '1a6', 'Index Middle Baby on Hinge', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('168', '1a7', 'Ring Hinge', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('169', '1a8', 'Index Middle Baby on Angle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('170', '1a9', 'Index Middle Cross with Baby', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('171', '1aa', 'Index Middle Cross with Baby on Circle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('172', '1ab', 'Ring Down', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('173', '1ac', 'Ring Down - Index Thumb Hook - Middle Hinge', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('174', '1ad', 'Ring Down - Middle Thumb Angle - Index Cross', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('175', '1ae', 'Ring Up', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('176', '1af', 'Ring Raised Knuckle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('177', '1b0', 'Ring Baby', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('178', '1b1', 'Ring Baby on Circle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('179', '1b2', 'Ring Baby on Oval', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('180', '1b3', 'Ring Baby on Angle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('181', '1b4', 'Ring Middle', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('182', '1b5', 'Ring Middle Unit', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('183', '1b6', 'Ring Middle Raised Knuckles', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('184', '1b7', 'Ring Index', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('185', '1b8', 'Ring Thumb', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('186', '1b9', 'Ring Thumb Hook', '1a4');
insert into glossario_cm ("id", "bsw", "name", "group") values ('187', '1ba', 'Index Ring Baby', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('188', '1bb', 'Index Ring Baby on Circle', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('189', '1bc', 'Index Ring Baby on Curlicue', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('190', '1bd', 'Index Ring Baby on Hook Out', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('191', '1be', 'Index Ring Baby on Hook In', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('192', '1bf', 'Index Ring Baby on Hook Under', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('193', '1c0', 'Index Ring Baby on Cup', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('194', '1c1', 'Index Ring Baby on Hinge', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('195', '1c2', 'Index Ring Baby on Angle Out', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('196', '1c3', 'Index Ring Baby on Angle', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('197', '1c4', 'Middle Down', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('198', '1c5', 'Middle Hinge', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('199', '1c6', 'Middle Up', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('200', '1c7', 'Middle Up on Circle', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('201', '1c8', 'Middle Raised Knuckle', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('202', '1c9', 'Middle Up - Thumb Side', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('203', '1ca', 'Middle Thumb Hook', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('204', '1cb', 'Middle Thumb Baby', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('205', '1cc', 'Middle Baby', '1ba');
insert into glossario_cm ("id", "bsw", "name", "group") values ('206', '1cd', 'Middle Ring Baby', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('207', '1ce', 'Middle Ring Baby on Circle', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('208', '1cf', 'Middle Ring Baby on Curlicue', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('209', '1d0', 'Middle Ring Baby on Cup', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('210', '1d1', 'Middle Ring Baby on Hinge', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('211', '1d2', 'Middle Ring Baby on Angle Out', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('212', '1d3', 'Middle Ring Baby on Angle In', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('213', '1d4', 'Middle Ring Baby on Angle', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('214', '1d5', 'Middle Ring Baby Bent', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('215', '1d6', 'Middle Ring Baby Unit on Claw', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('216', '1d7', 'Middle Ring Baby Unit on Claw Side', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('217', '1d8', 'Middle Ring Baby Unit on Hook Out', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('218', '1d9', 'Middle Ring Baby Unit on Hook In', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('219', '1da', 'Middle Ring Baby Unit on Hook', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('220', '1db', 'Index Hinge', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('221', '1dc', 'Index Thumb Side', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('222', '1dd', 'Index Thumb Side on Hinge', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('223', '1de', 'Index Thumb Side - Thumb Diagonal', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('224', '1df', 'Index Thumb Side - Thumb Unit', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('225', '1e0', 'Index Thumb Side - Thumb Bent', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('226', '1e1', 'Index Thumb Side - Index Bent', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('227', '1e2', 'Index Thumb Side - Both Bent', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('228', '1e3', 'Index Thumb Side - Index Hinge', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('229', '1e4', 'Index Thumb Forward - Index Straight', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('230', '1e5', 'Index Thumb Forward - Index Bent', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('231', '1e6', 'Index Thumb Hook', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('232', '1e7', 'Index Thumb Curlicue', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('233', '1e8', 'Index Thumb Curve - Thumb Inside', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('234', '1e9', 'Index Thumb Curve - Thumb Inside on Claw', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('235', '1ea', 'Index Thumb Curve - Thumb Under', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('236', '1eb', 'Index Thumb Circle', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('237', '1ec', 'Index Thumb Cup', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('238', '1ed', 'Index Thumb Cup Open', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('239', '1ee', 'Index Thumb Hinge Open', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('240', '1ef', 'Index Thumb Hinge Large', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('241', '1f0', 'Index Thumb Hinge', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('242', '1f1', 'Index Thumb Hinge Small', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('243', '1f2', 'Index Thumb Angle Out', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('244', '1f3', 'Index Thumb Angle In', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('245', '1f4', 'Index Thumb Angle', '1cd');
insert into glossario_cm ("id", "bsw", "name", "group") values ('246', '1f5', 'Thumb', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('247', '1f6', 'Thumb Heel', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('248', '1f7', 'Thumb Side Diagonal', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('249', '1f8', 'Thumb Side Unit', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('250', '1f9', 'Thumb Side Bent', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('251', '1fa', 'Thumb Forward', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('252', '1fb', 'Thumb Between Index Middle', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('253', '1fc', 'Thumb Between Middle Ring', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('254', '1fd', 'Thumb Between Ring Baby', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('255', '1fe', 'Thumb Under Two Fingers', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('256', '1ff', 'Thumb Over Two Fingers', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('257', '200', 'Thumb Under Three Fingers', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('258', '201', 'Thumb Under Four Fingers', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('259', '202', 'Thumb Over Four Raised Knuckles', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('260', '203', 'Fist', '1f5');
insert into glossario_cm ("id", "bsw", "name", "group") values ('261', '204', 'Fist Heel', '1f5');
COMMIT;
