version: '3'

# volumes:
#   data:

services:

  glossario:
    restart: always
    build: ../.
    volumes:
      - ../.:/code
    ports:
      - 8000:8000
    depends_on:
      - db_gll
    # links:
    #   - db_gll

  db_gll:
    # restart: always
    image: mysql:5.6.30
    # ports:
    #   - 3306:3306
    # volumes:
    #   - data:/var/lib/mysql
    environment:
            MYSQL_ROOT_PASSWORD: glossario
            MYSQL_DATABASE: glossario


  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   links:
  #     - db_gll
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1

  # networks:
#   default:
#   proxy-network:
#     #name: proxy-network
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.0.0/16