version: "3.1"

volumes:
  media_gll:
    driver: local
    driver_opts:
      type: ceph
      o: name=user,secret=pass
      device: ip:porta:pasta

services:
  glossario:
    image: ramonufsc/glossario:latest
    ports:
        - 40110:8000
    volumes:
        - media_gll:/code/media
