version: '3.2'

services:
  glossario:
    container_name: glossario_container
    restart: always
    build: ../.
    tty: true
    command: sh -c "python3 manage.py migrate &&
            python3 manage.py collectstatic --noinput &&
            gunicorn glossariolibras.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../.:/code
    env_file:
      - ./.env.dev
    expose:
      - 8000
    depends_on:
      - db_postgres
    environment:
      - POSTGRES_DB=libras
      - POSTGRES_USER=libras
      - POSTGRES_PASSWORD=libras
      - POSTGRES_DB_HOST=db_postgres
      - EMAIL_HOST_USER=libras
      - EMAIL_HOST_PASSWORD=libras

  nginx:
    build: ./nginx
    volumes:
      - ../.:/code
    ports:
      - 1337:80
    depends_on:
      - glossario

  db_postgres:
    image: postgres:9.6.6
    container_name: db_postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=libras
      - POSTGRES_USER=libras
      - POSTGRES_PASSWORD=libras
      - EMAIL_HOST_USER=libras
      - EMAIL_HOST_PASSWORD=libras