version: "3.2"

volumes:
  media_gll:
    driver: local
    driver_opts:
      type: ceph
      o: name=user,secret=pass
      device: ip:porta:pasta

services:
  glossario:
    restart: always
    image: ramonufsc/glossario:latest
    environment:
      - POSTGRES_DB=glossariolibras
      - POSTGRES_USER=glossariolibras
      - POSTGRES_PASSWORD=igh9Viev
      - POSTGRES_DB_HOST=libras
      - EMAIL_HOST_USER=libras
      - EMAIL_HOST_PASSWORD=l1br4sufsc
    ports:
        - 40110:8000
    volumes:
        - media_gll:/code/media
