version: '3.2'

services:
  glossario:
    build: ../.
    volumes:
      - ../.:/code
    ports:
      - 8000:8000
    depends_on:
      - db_postgres
    environment:
      - POSTGRES_DB=libras
      - POSTGRES_USER=libras
      - POSTGRES_PASSWORD=libras
      - EMAIL_HOST_USER=libras
      - EMAIL_HOST_PASSWORD=libras

  db_postgres:
    image: postgres:9.6.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=libras
      - POSTGRES_USER=libras
      - POSTGRES_PASSWORD=libras
      - EMAIL_HOST_USER=libras
      - EMAIL_HOST_PASSWORD=libras

